name: CI
on:
  [push, pull_request]
jobs:
  generic-build-test:
    runs-on: ubuntu-latest
    if: "!contains(github.ref, 'coverity_scan')"
    strategy:
      matrix:
        docker_image: [ubuntu-18.04, ubuntu-20.04, fedora-32, opensuse-leap]
        compiler: [gcc, clang]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Launch Container
        env:
          DOCKER_IMAGE: ${{ matrix.docker_image }}
          CC: ${{ matrix.compiler }}
          BASE_REF: ${{ github.base_ref }}
        run: |
          ./.ci/travis.run
      - name: failure
        if: ${{ failure() }}
        run: cat $(find ../ -name test-suite.log) || true
  scanbuild:
    runs-on: ubuntu-latest
    if: "!contains(github.ref, 'coverity_scan')"
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Launch Container
        env:
          CC: clang
          DOCKER_IMAGE: fedora-32
          SCANBUILD: yes
        run: ./.ci/travis.run
      - name: failure
        if: ${{ failure() }}
        run: cat $(find ../ -name test-suite.log) || true
  test-coverage:
    runs-on: ubuntu-latest
    if: "!contains(github.ref, 'coverity_scan')"
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Launch Container
        env:
          CC: gcc
          DOCKER_IMAGE: ubuntu-18.04
          ENABLE_COVERAGE: true
        run: ./.ci/travis.run
      - name: failure
        if: ${{ failure() }}
        run: cat $(find ../ -name test-suite.log) || true
  test-fuzz:
    runs-on: ubuntu-latest
    if: "!contains(github.ref, 'coverity_scan')"
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Launch Container
        env:
          DOCKER_IMAGE: fedora-32
          GEN_FUZZ: 1
          CXX: clang++
          CC: clang
        run: ./.ci/travis.run
      - name: failure
        if: ${{ failure() }}
        run: cat $(find ../ -name test-suite.log) || true
  coverity-test:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'coverity_scan')
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Launch Container
        env:
          REPO_BRANCH: ${{ github.ref }}
          REPO_SLUG: ${{ github.repository }}
          ENABLE_COVERITY: true
          DOCKER_IMAGE: ubuntu-18.04
          CC: gcc
          COVERITY_SCAN_TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
          COVERITY_SUBMISSION_EMAIL: tadeusz.struk@intel.com
        run: ./.ci/travis.run
      - name: failure
        if: ${{ failure() }}
        run: cat $(find ../ -name test-suite.log) || true
